import React from 'react';
import { StageType, Language } from './types';
import { 
  Heart, 
  Search, 
  Lightbulb, 
  Hammer, 
  ClipboardCheck, 
  Rocket,
} from 'lucide-react';

export const TRANSLATIONS = {
  en: {
    appTitle: "DesignThinker Pro",
    slogan: "Start your innovation journey.",
    setupTitle: "Project Setup",
    projectName: "Project Title",
    studentName: "Student / Group Name",
    email: "Email Address",
    studentId: "Student ID (10 Digits)",
    projectType: "Project Type",
    individual: "Individual Project",
    group: "Group Project",
    start: "Start Project",
    instructorLogin: "Instructor Access",
    adminDashboard: "Admin Dashboard",
    uploadCsv: "Upload Student IDs (CSV)",
    validIds: "Valid IDs",
    registeredUsers: "Registered Users",
    online: "Online",
    offline: "Offline",
    signOut: "Sign Out",
    profile: "Profile Settings",
    dashboard: "Dashboard",
    viewReport: "View Report",
    settings: "Settings",
    language: "Language",
    verified: "Verified",
    changeAvatar: "Change Avatar",
    stage: "Stage",
    weight: "Weight",
    score: "Score",
    feedback: "Instructor Feedback",
    aiHelp: "AI Assistant",
    upload: "Upload",
    submit: "Submit for Review",
    approve: "Approve & Next",
    reject: "Reject",
    backToCycle: "Back to Cycle",
    workOptions: "Work Options",
    addOption: "Add Option",
    requirements: "Requirements",
    grading: "Grading & Actions",
    loginError: "Invalid credentials.",
    idError: "Student ID not found in system. Please contact administrator.",
    csvSuccess: "Student IDs updated successfully.",
    menu: "Navigation",
    instructorPanel: "Instructor Panel",
    studentView: "Student View",
    fitScreen: "Fit to Screen",
    resetView: "Reset View",
    toolPan: "Pan Tool",
    toolAnnotate: "Annotate Tool",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    // New
    exportResults: "Export Results (CSV)",
    annotationNotes: "Feedback Notes",
    addNotePlaceholder: "Explain the issue here...",
    noNotes: "No notes added yet."
  },
  vi: {
    appTitle: "DesignThinker Pro",
    slogan: "Bắt đầu hành trình sáng tạo của bạn.",
    setupTitle: "Thiết lập dự án",
    projectName: "Tên dự án",
    studentName: "Tên Sinh viên / Nhóm",
    email: "Địa chỉ Email",
    studentId: "Mã số sinh viên (10 số)",
    projectType: "Loại dự án",
    individual: "Cá nhân",
    group: "Nhóm",
    start: "Bắt đầu dự án",
    instructorLogin: "Đăng nhập Giảng viên",
    adminDashboard: "Bảng điều khiển Quản trị",
    uploadCsv: "Tải lên danh sách MSSV (CSV)",
    validIds: "Mã hợp lệ",
    registeredUsers: "Sinh viên đã đăng ký",
    online: "Trực tuyến",
    offline: "Ngoại tuyến",
    signOut: "Đăng xuất",
    profile: "Cài đặt tài khoản",
    dashboard: "Bảng điều khiển",
    viewReport: "Xem báo cáo",
    settings: "Cài đặt",
    language: "Ngôn ngữ",
    verified: "Đã xác thực",
    changeAvatar: "Đổi ảnh đại diện",
    stage: "Giai đoạn",
    weight: "Trọng số",
    score: "Điểm",
    feedback: "Nhận xét của Giảng viên",
    aiHelp: "Trợ lý AI",
    upload: "Tải lên",
    submit: "Nộp bài",
    approve: "Duyệt & Tiếp theo",
    reject: "Yêu cầu làm lại",
    backToCycle: "Quay lại Quy trình",
    workOptions: "Các phương án",
    addOption: "Thêm phương án",
    requirements: "Yêu cầu",
    grading: "Chấm điểm & Thao tác",
    loginError: "Thông tin đăng nhập không đúng.",
    idError: "Mã số sinh viên không tồn tại trong hệ thống. Vui lòng liên hệ quản trị viên.",
    csvSuccess: "Cập nhật danh sách MSSV thành công.",
    menu: "Điều hướng",
    instructorPanel: "Bảng Giảng viên",
    studentView: "Màn hình Sinh viên",
    fitScreen: "Vừa màn hình",
    resetView: "Mặc định",
    toolPan: "Công cụ Di chuyển",
    toolAnnotate: "Công cụ Ghi chú",
    zoomIn: "Phóng to",
    zoomOut: "Thu nhỏ",
    // New
    exportResults: "Xuất Kết quả (CSV)",
    annotationNotes: "Ghi chú chi tiết",
    addNotePlaceholder: "Giải thích lỗi sai tại đây...",
    noNotes: "Chưa có ghi chú nào."
  }
};

export const STAGE_CONFIG = {
  [StageType.EMPATHIZE]: {
    label: 'Empathize',
    color: 'text-blue-500',
    bgColor: 'bg-blue-500',
    bgLight: 'bg-blue-50',
    borderColor: 'border-blue-500',
    icon: <Heart className="w-6 h-6" />,
    description: 'Conduct research to develop an understanding of your users.'
  },
  [StageType.DEFINE]: {
    label: 'Define',
    color: 'text-blue-700',
    bgColor: 'bg-blue-700',
    bgLight: 'bg-blue-100',
    borderColor: 'border-blue-700',
    icon: <Search className="w-6 h-6" />,
    description: 'Combine all your research and observe where your users\' problems exist.'
  },
  [StageType.IDEATE]: {
    label: 'Ideate',
    color: 'text-orange-500',
    bgColor: 'bg-orange-500',
    bgLight: 'bg-orange-50',
    borderColor: 'border-orange-500',
    icon: <Lightbulb className="w-6 h-6" />,
    description: 'Generate a range of crazy, creative ideas.'
  },
  [StageType.PROTOTYPE]: {
    label: 'Prototype',
    color: 'text-yellow-500',
    bgColor: 'bg-yellow-500',
    bgLight: 'bg-yellow-50',
    borderColor: 'border-yellow-500',
    icon: <Hammer className="w-6 h-6" />,
    description: 'Build real, tactile representations for a range of your ideas.'
  },
  [StageType.TEST]: {
    label: 'Test',
    color: 'text-yellow-700',
    bgColor: 'bg-yellow-700',
    bgLight: 'bg-yellow-100',
    borderColor: 'border-yellow-700',
    icon: <ClipboardCheck className="w-6 h-6" />,
    description: 'Return to your users for feedback.'
  },
  [StageType.IMPLEMENT]: {
    label: 'Implement/Materialize',
    color: 'text-purple-600',
    bgColor: 'bg-purple-600',
    bgLight: 'bg-purple-50',
    borderColor: 'border-purple-600',
    icon: <Rocket className="w-6 h-6" />,
    description: 'Put the vision into effect.'
  }
};